version: "3.9"

services:
  osf_app:
    build: .
    container_name: open_synth_fi_app
    command: uvicorn open_synth_fi.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./open_synth_fi:/code/open_synth_fi
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - osf_db

  osf_db:
    image: postgres:16
    container_name: open_synth_fi_db
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
